#!/bin/bash

# Generate RSA Keys
cd ServerKeys
python3 ../Programs/RSAKeyGeneration/makeRSAKeyPair.py Server 4096 -d `pwd`
cd ../ClientKeys
python3 ../Programs/RSAKeyGeneration/makeRSAKeyPair.py Client 4096 -d `pwd`
